version: 2

defaults: &defaults
  working_directory: /go/src/github.com/zchee/cil

jobs:
  checkout:
    docker:
      - image: scratch
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: /go/src/github.com/zchee/cil
          paths:
            - "*"

  build-linux:
    docker:
      - image: golang:1.11-rc-stretch
    <<: *defaults
    steps:
      - attach_workspace:
          at: /go/src/github.com/zchee/cil
      - run:
          name: Test and take a coverage
          environment:
          command: |
            make coverage
      - run:
          name: Send coverage reports to codecov.io
          command: |
            bash <(curl -s https://codecov.io/bash)

  build-macos:
    macos:
      xcode: 9.4.0
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    <<: *defaults
    steps:
      - attach_workspace:
          at: /go/src/github.com/zchee/cil
      - run:
          name: Install latest go formula
          command: |
            brew install https://github.com/Homebrew/homebrew-core/raw/master/Formula/go.rb
            mkdir -p $HOME/go
            export PATH="$HOME/go/bin:$PATH"
            go version
      - run:
          naMe: Show kernel versions
          command: |
            uname -a
            sw_vers
            xcodebuild -version
            system_profiler SPHardwareDataType
      - run:
          name: Test and take a coverage
          environment:
          command: |
            make coverage
      - run:
          name: Send coverage reports to codecov.io
          command: |
            bash <(curl -s https://codecov.io/bash)

  reviewdog:
    docker:
      - image: golang:1.11-rc-stretch
    <<: *defaults
    steps:
      - attach_workspace:
          at: /go/src/github.com/zchee/cil
      - run:
          name: Install linter tools
          command: |
            make lint.install
      - run:
          name: reviewdog
          command: |
            go get -u -v github.com/haya14busa/reviewdog/cmd/reviewdog
            reviewdog -reporter="github-pr-review"

workflows:
  version: 2
  workflows:
    jobs:
      - checkout
      - build-linux:
          requires:
            - checkout
      - build-macos:
          requires:
            - checkout
      - reviewdog:
          context: org-global
          requires:
            - checkout
          filters:
            branches:
              ignore: master
