/*
 * CircleCI API
 *
 * The CircleCI API is a fully-featured JSON API that allows you to access all information and trigger all actions in CircleCI. 
 *
 * API version: v1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package circleci

type Branch struct {

	PusherLogins []string `json:"pusher_logins,omitempty"`

	LatestWorkflows *BuildWorkflow `json:"latest_workflows,omitempty"`

	LatestCompletedWorkflows *BuildWorkflow `json:"latest_completed_workflows,omitempty"`

	LastNonSuccess *BuildSummary `json:"last_non_success,omitempty"`

	LastSuccess *BuildSummary `json:"last_success,omitempty"`

	RecentBuilds *BuildSummary `json:"recent_builds,omitempty"`

	RunningBuilds *Builds `json:"running_builds,omitempty"`
}
