/*
 * CircleCI API
 *
 * The CircleCI API is a fully-featured JSON API that allows you to access all information and trigger all actions in CircleCI. 
 *
 * API version: v1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package circleci

import (
	"time"
)

// previous build
type BuildDetail struct {

	AllCommitDetails *CommitDetails `json:"all_commit_details,omitempty"`

	Compare string `json:"compare,omitempty"`

	JobName string `json:"job_name,omitempty"`

	PreviousSuccessfulBuild *PreviousBuild `json:"previous_successful_build,omitempty"`

	Retries bool `json:"retries,omitempty"`

	SshEnabled bool `json:"ssh_enabled,omitempty"`

	Timedout bool `json:"timedout,omitempty"`

	UsageQueuedAt time.Time `json:"usage_queued_at,omitempty"`

	User *User `json:"user,omitempty"`
}
