/*
 * CircleCI API
 *
 * The CircleCI API is a fully-featured JSON API that allows you to access all information and trigger all actions in CircleCI. 
 *
 * API version: v1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package circleci

import (
	"time"
)

type Build struct {

	// commit message body
	Body string `json:"body,omitempty"`

	Branch string `json:"branch,omitempty"`

	BuildTimeMillis int32 `json:"build_time_millis,omitempty"`

	BuildUrl string `json:"build_url,omitempty"`

	CommitterEmail string `json:"committer_email,omitempty"`

	CommitterName string `json:"committer_name,omitempty"`

	// reason why we didn't build, if we didn't build
	DontBuild string `json:"dont_build,omitempty"`

	Lifecycle string `json:"lifecycle,omitempty"`

	Previous *PreviousBuild `json:"previous,omitempty"`

	// time build was queued
	QueuedAt time.Time `json:"queued_at,omitempty"`

	Reponame string `json:"reponame,omitempty"`

	// build_num of the build this is a retry of
	RetryOf int32 `json:"retry_of,omitempty"`

	// time build started
	StartTime time.Time `json:"start_time,omitempty"`

	// time build finished
	StopTime time.Time `json:"stop_time,omitempty"`

	Subject string `json:"subject,omitempty"`

	Username string `json:"username,omitempty"`

	VcsUrl string `json:"vcs_url,omitempty"`

	// short string explaining the reason we built
	Why string `json:"why,omitempty"`

	Workflows *Workflows `json:"workflows,omitempty"`
}
