/*
 * CircleCI API
 *
 * The CircleCI API is a fully-featured JSON API that allows you to access all information and trigger all actions in CircleCI. 
 *
 * API version: v1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package circleci

import (
	"time"
)

type BuildSummary struct {

	AddedAt time.Time `json:"added_at,omitempty"`

	BuildNum int32 `json:"build_num,omitempty"`

	Outcome string `json:"outcome,omitempty"`

	PushedAt time.Time `json:"pushed_at,omitempty"`

	Status *Status `json:"status,omitempty"`

	VcsRevision *Sha1 `json:"vcs_revision,omitempty"`

	IsWorkflowJob bool `json:"is_workflow_job,omitempty"`
}
