/*
 * CircleCI API
 *
 * The CircleCI API is a fully-featured JSON API that allows you to access all information and trigger all actions in CircleCI. 
 *
 * API version: v1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package circleci

type Identitiy struct {

	AvatarUrl string `json:"avatar_url,omitempty"`

	ExternalId string `json:"external_id,omitempty"`

	Id string `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	User bool `json:"user?,omitempty"`

	Domain string `json:"domain,omitempty"`

	Type_ string `json:"type,omitempty"`

	Authorized bool `json:"authorized?,omitempty"`

	ProviderId string `json:"provider_id,omitempty"`

	Login string `json:"login,omitempty"`
}
