/*
 * CircleCI API
 *
 * The CircleCI API is a fully-featured JSON API that allows you to access all information and trigger all actions in CircleCI. 
 *
 * API version: v1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package circleci

import (
	"time"
)

type Key struct {

	Fingerprint string `json:"fingerprint,omitempty"`

	Preferred bool `json:"preferred,omitempty"`

	PublicKey string `json:"public_key,omitempty"`

	// when the key was issued
	Time time.Time `json:"time,omitempty"`

	// can be 'deploy-key' or 'github-user-key'
	Type_ string `json:"type,omitempty"`
}
