/*
 * CircleCI API
 *
 * The CircleCI API is a fully-featured JSON API that allows you to access all information and trigger all actions in CircleCI. 
 *
 * API version: v1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package circleci

// previous build
type PreviousBuild struct {

	BuildNum int32 `json:"build_num,omitempty"`

	BuildTimeMillis int32 `json:"build_time_millis,omitempty"`

	Status *Status `json:"status,omitempty"`
}
