/*
 * CircleCI API
 *
 * The CircleCI API is a fully-featured JSON API that allows you to access all information and trigger all actions in CircleCI. 
 *
 * API version: v1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package circleci

type ProjectFeatureFlags struct {

	BuildForkPrs bool `json:"build-fork-prs,omitempty"`

	Fleet bool `json:"fleet,omitempty"`

	Junit bool `json:"junit,omitempty"`

	Oss bool `json:"oss,omitempty"`

	Osx bool `json:"osx,omitempty"`

	SetGithubStatus bool `json:"set-github-status,omitempty"`

	TrustyBeta bool `json:"trusty-beta,omitempty"`
}
