/*
 * CircleCI API
 *
 * The CircleCI API is a fully-featured JSON API that allows you to access all information and trigger all actions in CircleCI. 
 *
 * API version: v1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package circleci

type Status string

// List of Status
const (
	CANCELED Status = "canceled"
	FAILED Status = "failed"
	FIXED Status = "fixed"
	INFRASTRUCTURE_FAIL Status = "infrastructure_fail"
	NO_TESTS Status = "no_tests"
	NOT_RUN Status = "not_run"
	NOT_RUNNING Status = "not_running"
	QUEUED Status = "queued"
	RETRIED Status = "retried"
	RUNNING Status = "running"
	SCHEDULED Status = "scheduled"
	SUCCESS Status = "success"
	TIMEDOUT Status = "timedout"
)
