/*
 * CircleCI API
 *
 * The CircleCI API is a fully-featured JSON API that allows you to access all information and trigger all actions in CircleCI. 
 *
 * API version: v1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package circleci

type TestsTests struct {

	Classname string `json:"classname,omitempty"`

	File string `json:"file,omitempty"`

	Message string `json:"message,omitempty"`

	Name string `json:"name,omitempty"`

	Result *Status `json:"result,omitempty"`

	RunTime float32 `json:"run_time,omitempty"`

	Source string `json:"source,omitempty"`
}
