/*
 * CircleCI API
 *
 * The CircleCI API is a fully-featured JSON API that allows you to access all information and trigger all actions in CircleCI. 
 *
 * API version: v1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package circleci

import (
	"time"
)

type User struct {

	Admin bool `json:"admin,omitempty"`

	AllEmails []string `json:"all_emails,omitempty"`

	AnalyticsId string `json:"analytics_id,omitempty"`

	AvatarUrl string `json:"avatar_url,omitempty"`

	BasicEmailPrefs string `json:"basic_email_prefs,omitempty"`

	Bitbucket *interface{} `json:"bitbucket,omitempty"`

	BitbucketAuthorized bool `json:"bitbucket_authorized,omitempty"`

	Containers int64 `json:"containers,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	DaysLeftInTrial int64 `json:"days_left_in_trial,omitempty"`

	DevAdmin bool `json:"dev_admin,omitempty"`

	EnrolledBetas []string `json:"enrolled_betas,omitempty"`

	FirstVcsAuthorizedClientId *StringOrNull `json:"first_vcs_authorized_client_id,omitempty"`

	GithubId int64 `json:"github_id,omitempty"`

	GithubOauthScopes []string `json:"github_oauth_scopes,omitempty"`

	GravatarId int64 `json:"gravatar_id,omitempty"`

	HerokuApiKey string `json:"heroku_api_key,omitempty"`

	Identities *UserIdentities `json:"identities,omitempty"`

	InBetaProgram bool `json:"in_beta_program,omitempty"`

	Login string `json:"login,omitempty"`

	Name string `json:"name,omitempty"`

	NumProjectsFollowed int64 `json:"num_projects_followed,omitempty"`

	OrganizationPrefs *interface{} `json:"organization_prefs,omitempty"`

	Parallelism int64 `json:"parallelism,omitempty"`

	Plan string `json:"plan,omitempty"`

	Projects *interface{} `json:"projects,omitempty"`

	PusherId string `json:"pusher_id,omitempty"`

	SelectedEmail string `json:"selected_email,omitempty"`

	SignInCount int64 `json:"sign_in_count,omitempty"`

	Student bool `json:"student,omitempty"`

	TrialEnd time.Time `json:"trial_end,omitempty"`
}
