/*
 * CircleCI API
 *
 * The CircleCI API is a fully-featured JSON API that allows you to access all information and trigger all actions in CircleCI. 
 *
 * API version: v1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package circleci

type Workflows struct {

	JobName string `json:"job_name,omitempty"`

	JobId string `json:"job_id,omitempty"`

	WorkflowId string `json:"workflow_id,omitempty"`

	WorkspaceId string `json:"workspace_id,omitempty"`

	UpstreamJobIds []string `json:"upstream_job_ids,omitempty"`

	UpstreamConcurrencyMap []string `json:"upstream_concurrency_map,omitempty"`

	WorkflowName string `json:"workflow_name,omitempty"`
}
